### ISSUE TITLE
Sweep: Add title 'bananaweb' to https://github.com/BananaBake/my-website/blob/5efaad358b78f6c15e650bba4eae6f5fe733fd94/index.html

### ISSUE THREAD

**Issue by BananaBake** [BananaBake/my-website#7]
Sweep: Add the title to the index.html

<details>
<summary>Checklist</summary>

- [X] `index.html`
> * Add a head section to the HTML document. This should be added before the body section.
> • Within the head section, add a title tag.
> • Set the value of the title tag to 'bananaweb'.

</details>

**Comment by kevinlu1248** [comment]
Hey @BananaBake, Sweep doesn't really work well on test repos. Please try this on a real repo to see Sweep do something meaningful successfully.
